set_property PACKAGE_PIN N5 [get_ports o_AN3_out]
set_property PACKAGE_PIN N6 [get_ports o_AN0_out]
set_property PACKAGE_PIN M6 [get_ports o_AN1_out]
set_property PACKAGE_PIN M3 [get_ports o_AN2_out]
set_property PACKAGE_PIN N2 [get_ports o_AN4_out]
set_property PACKAGE_PIN N4 [get_ports o_AN5_out]
set_property PACKAGE_PIN L1 [get_ports o_AN6_out]
set_property PACKAGE_PIN M1 [get_ports o_AN7_out]
set_property PACKAGE_PIN L3 [get_ports o_segmentlight_out[0]]
set_property PACKAGE_PIN N1 [get_ports o_segmentlight_out[1]]
set_property PACKAGE_PIN L5 [get_ports o_segmentlight_out[2]]
set_property PACKAGE_PIN L4 [get_ports o_segmentlight_out[3]]
set_property PACKAGE_PIN K3 [get_ports o_segmentlight_out[4]]
set_property PACKAGE_PIN M2 [get_ports o_segmentlight_out[5]]
set_property PACKAGE_PIN L6 [get_ports o_segmentlight_out[6]]
set_property PACKAGE_PIN U9 [get_ports i_segment[0]]
set_property PACKAGE_PIN U8 [get_ports i_segment[1]]
set_property PACKAGE_PIN R7 [get_ports i_segment[2]]
set_property PACKAGE_PIN R6 [get_ports i_segment[3]]
set_property PACKAGE_PIN R5 [get_ports i_segment[4]]
set_property PACKAGE_PIN V7 [get_ports i_segment[5]]
set_property PACKAGE_PIN V6 [get_ports i_segment[6]]
set_property PACKAGE_PIN V5 [get_ports i_segment[7]]
set_property PACKAGE_PIN U4 [get_ports i_segment[8]]
set_property PACKAGE_PIN V2 [get_ports i_segment[9]]
set_property IOSTANDARD LVCMOS33 [get_ports o_AN3_out]
set_property IOSTANDARD LVCMOS33 [get_ports o_AN0_out]
set_property IOSTANDARD LVCMOS33 [get_ports o_AN1_out]
set_property IOSTANDARD LVCMOS33 [get_ports o_AN2_out]
set_property IOSTANDARD LVCMOS33 [get_ports o_AN4_out]
set_property IOSTANDARD LVCMOS33 [get_ports o_AN5_out]
set_property IOSTANDARD LVCMOS33 [get_ports o_AN6_out]
set_property IOSTANDARD LVCMOS33 [get_ports o_AN7_out]
set_property IOSTANDARD LVCMOS33 [get_ports o_segmentlight_out*]
set_property IOSTANDARD LVCMOS33 [get_ports i_segment*]




